/* The demo catalogue: the contracted shops and everything on their counters.

   One record holds both languages. The alternative — English in model.mjs and
   Mongolian in i18n.js, joined only by a string id — is two lists that drift
   apart the first time somebody adds an item, and with six shops and a hundred
   and twenty items that is not a matter of if. i18n.js reads the Mongolian
   column out of here and publishes it under the same `demo.*` keys the
   interface already looks up, so nothing downstream had to learn a new shape.

   Shop coordinates are real places in Ulaanbaatar, because "350 m away" should
   be arithmetic and not a hard-coded string. Prices, stock, pickup windows and
   the shops themselves are invented for this preview. */

export const CATEGORIES = ['Bakery', 'Meals', 'Sweet', 'Drinks', 'Grocery'];

/* Districts are the ones a person in Ulaanbaatar would name, held as ids so
   the value stored in state never changes with the reader's language. */
export const DISTRICTS = [
  { id: 'all', key: 'district.all', en: 'All of Ulaanbaatar' },
  { id: 'sukhbaatar', key: 'district.sukhbaatar', en: 'Sükhbaatar' },
  { id: 'chingeltei', key: 'district.chingeltei', en: 'Chingeltei' },
  { id: 'bayangol', key: 'district.bayangol', en: 'Bayangol' },
  { id: 'bayanzurkh', key: 'district.bayanzurkh', en: 'Bayanzürkh' },
  { id: 'khanuul', key: 'district.khanuul', en: 'Khan-Uul' },
];

export const SHOPS = [
  {
    id: 'm1', name: 'Little Loaf', rating: 4.8, ratings: 312, rescued: 2140, since: '2026-01', district: 'chingeltei', lat: 47.9186, lng: 106.9098,
    en: { kind: 'Neighbourhood bakery', address: 'Peace Avenue, near the State Department Store', pickupNote: 'Come to the bakery counter and show your pickup pass.' },
    mn: { kind: 'Хорооллын талхны газар', address: 'Энх тайвны өргөн чөлөө, Улсын их дэлгүүрийн ойролцоо', pickupNote: 'Талхны лангуу дээр ирж очиж авах pass-аа үзүүлнэ үү.' },
  },
  {
    id: 'm2', name: 'Seoul Kitchen', rating: 4.6, ratings: 198, rescued: 1370, since: '2026-02', district: 'sukhbaatar', lat: 47.9139, lng: 106.9160,
    en: { kind: 'Korean kitchen', address: 'Seoul Street, central Ulaanbaatar', pickupNote: 'Ask for your Monty order at the front counter.' },
    mn: { kind: 'Солонгос хоолны газар', address: 'Сөүлийн гудамж, Улаанбаатарын төв', pickupNote: 'Урд талын лангуу дээр Monty захиалгаа асууна уу.' },
  },
  {
    id: 'm3', name: 'Orchard Café', rating: 4.9, ratings: 241, rescued: 1585, since: '2026-03', district: 'sukhbaatar', lat: 47.9205, lng: 106.9192,
    en: { kind: 'Café and patisserie', address: 'Near Sükhbaatar Square, central Ulaanbaatar', pickupNote: 'Your order will be waiting at the café counter.' },
    mn: { kind: 'Кафе, нарийн боовны газар', address: 'Сүхбаатарын талбайн ойролцоо, Улаанбаатарын төв', pickupNote: 'Таны захиалга кафены лангуун дээр хүлээж байх болно.' },
  },
  {
    id: 'm4', name: 'Steppe Table', mnName: 'Тал Ширээ', rating: 4.7, ratings: 164, rescued: 1490, since: '2026-04', district: 'bayangol', lat: 47.9142, lng: 106.8712,
    en: { kind: 'Mongolian home cooking', address: 'Ard Kino Square, 3rd khoroolol, Bayangol', pickupNote: 'Come to the till and give your code to the cook.' },
    mn: { kind: 'Монгол гэрийн хоол', address: 'Ард кино театрын талбай, 3-р хороолол, Баянгол', pickupNote: 'Кассанд ирж кодоо тогоочид хэлээрэй.' },
  },
  {
    id: 'm5', name: 'Blue Sky Grocer', mnName: 'Хөх Тэнгэр Дэлгүүр', rating: 4.4, ratings: 126, rescued: 2260, since: '2026-05', district: 'khanuul', lat: 47.8871, lng: 106.9285,
    en: { kind: 'Grocery and market stall', address: 'Zaisan road, Khan-Uul', pickupNote: 'Collect your box from the customer service desk by the entrance.' },
    mn: { kind: 'Хүнсний дэлгүүр, лангуу', address: 'Зайсангийн зам, Хан-Уул', pickupNote: 'Орох хаалганы дэргэдэх үйлчилгээний ширээнээс хайрцгаа аваарай.' },
  },
  {
    id: 'm6', name: 'Sansar Coffee House', mnName: 'Сансар Кофе', rating: 4.5, ratings: 143, rescued: 980, since: '2026-06', district: 'bayanzurkh', lat: 47.9219, lng: 106.9497,
    en: { kind: 'Coffee roastery', address: 'Sansar crossroads, Bayanzürkh', pickupNote: 'Tell the barista your code and they will hand your order over.' },
    mn: { kind: 'Кофе шарах газар', address: 'Сансарын уулзвар, Баянзүрх', pickupNote: 'Баристад кодоо хэлэхэд захиалгаа тань өгнө.' },
  },
];

/* Every item in one shop has to share a pickup window with every other, or a
   basket from that shop cannot be checked out. Two overlapping windows per
   shop is enough variety to look real and still always intersect. */
const LOAF_A = ['17:00', '19:00'];
const LOAF_B = ['17:30', '19:00'];
const LOAF_C = ['16:30', '19:30'];
const SEOUL_A = ['18:00', '20:00'];
const SEOUL_B = ['17:30', '20:30'];
const ORCHARD_A = ['16:30', '18:30'];
const ORCHARD_B = ['16:00', '19:00'];
const STEPPE_A = ['18:00', '20:30'];
const STEPPE_B = ['18:30', '21:00'];
const GROCER_A = ['19:00', '21:30'];
const GROCER_B = ['19:30', '22:00'];
const SANSAR_A = ['14:00', '17:00'];
const SANSAR_B = ['15:00', '17:30'];

/* `art` is either a bundled photograph or the name of a drawing in foodart.mjs.
   Five items carry real photographs, which is roughly the ratio a young
   marketplace actually has: a few shops send pictures, the rest get a drawing
   until they do. */
const item = (id, shop, category, art, price, originalPrice, quantity, window, allergens, en, mn) => ({
  id, shop, category, art, price, originalPrice, quantity,
  pickupStart: window[0], pickupEnd: window[1], allergens,
  en: { title: en[0], description: en[1] },
  mn: { title: mn[0], description: mn[1] },
});

export const ITEMS = [
  // ---- m1 · Little Loaf ---------------------------------------------------
  item('o1', 'm1', 'Bakery', '/assets/croissant.jpg', 3900, 7800, 8, LOAF_A, ['Wheat', 'Milk', 'Eggs'],
    ['Butter croissant', 'Golden, flaky layers and a soft buttery middle. Baked this morning, lovely with your afternoon coffee.'],
    ['Цөцгийн тосны круассан', 'Алтлаг, давхаргалаг гадаргуутай, зөөлөн цөцгийн тостой дунд хэсэгтэй. Өнөө өглөө шарсан, үдээс хойшхи кофетой тань гайхалтай зохицно.']),
  item('o2', 'm1', 'Sweet', '/assets/cinnamon.jpg', 4500, 9000, 5, LOAF_B, ['Wheat', 'Milk', 'Eggs'],
    ['Cinnamon roll', 'A soft swirl of cinnamon and brown sugar, baked until golden. A small, sweet end to the day.'],
    ['Шанцайны ороомог', 'Шанцай, хүрэн элсэн чихрийн зөөлөн ороомог, алтлаг болтол нь шарсан. Өдрийг дуусгах бяцхан амттан.']),
  item('o5', 'm1', 'Bakery', '/assets/bread.jpg', 7500, 15000, 4, LOAF_A, ['Wheat'],
    ['Sourdough loaf', 'A small, slowly fermented loaf with a crisp crust and a soft, open crumb. Made for tomorrow’s toast.'],
    ['Исгэсэн зуурмагийн талх', 'Удаан исгэсэн, хэврэг царцдастай, зөөлөн сүвэрхэг дотортой жижиг талх. Маргаашийн шарсан талханд тохирно.']),
  item('o6', 'm1', 'Bakery', 'baguette', 3200, 6400, 9, LOAF_A, ['Wheat'],
    ['Evening baguette', 'Long, thin and still crackling. Break it over dinner tonight, no knife needed.'],
    ['Оройн багет', 'Урт нарийхан, царцдас нь хэвээрээ шаржигнасан. Өнөө оройн хоолон дээр хутгагүйгээр хуваагаарай.']),
  item('o7', 'm1', 'Bakery', 'loaf', 4800, 9600, 6, LOAF_C, ['Wheat', 'Milk', 'Soy'],
    ['Wholewheat sandwich loaf', 'Sliced and ready. Soft enough for the children, hearty enough for a working lunch.'],
    ['Бүхэл буудайн сэндвичний талх', 'Зүсэж бэлдсэн. Хүүхдэд зөөлөн, ажлын өдрийн үдийн хоолонд ч хангалттай тослог.']),
  item('o8', 'm1', 'Bakery', 'rye', 5400, 10800, 5, LOAF_C, ['Wheat', 'Sesame'],
    ['Dark rye bread', 'Dense, faintly sour, and very good indeed with cold meat and mustard.'],
    ['Хар хөх тарианы талх', 'Нягт, бага зэрэг исгэлэн амттай. Хүйтэн мах, гичийтэй маш сайхан зохицно.']),
  item('o9', 'm1', 'Bakery', 'bagel', 2900, 5800, 12, LOAF_C, ['Wheat', 'Sesame'],
    ['Sesame bagel', 'Boiled first, then baked. A chewy middle under a lid of toasted sesame.'],
    ['Гүнжидтэй бэйгл', 'Эхлээд буцалгаад дараа нь шарсан. Зажлууртай дунд хэсэгтэй, дээрээ шарсан гүнжидтэй.']),
  item('o10', 'm1', 'Bakery', 'bun', 3400, 6800, 10, LOAF_A, ['Wheat', 'Milk', 'Eggs'],
    ['Cheese bun', 'A pillowy bun with melted cheese baked into the top. Two minutes in the oven and it is new again.'],
    ['Бяслагтай боов', 'Зөөлөн сэвсгэр боов, дээр нь бяслаг хайлуулан жигнэсэн. Хоёр минут халаахад дахин шинэ болно.']),
  item('o11', 'm1', 'Bakery', 'scone', 3100, 6200, 7, LOAF_B, ['Wheat', 'Milk', 'Eggs'],
    ['Raisin scone', 'Crumbly and barely sweet, made to be split in half and buttered.'],
    ['Үзэмтэй скон', 'Хэврэг, бага чихэрлэг. Хоёр хувааж, цөцгийн тос түрхэхэд яг таарна.']),
  item('o12', 'm1', 'Bakery', 'croissant', 4700, 9400, 6, LOAF_A, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Almond croissant', 'Yesterday’s croissant, filled with almond cream and baked again. Better the second time.'],
    ['Бүйлсний круассан', 'Өчигдрийн круассаныг бүйлсний тостой дүүргэж дахин шарсан. Хоёр дахь удаадаа илүү амттай.']),
  item('o13', 'm1', 'Sweet', 'babka', 6200, 12400, 4, LOAF_B, ['Wheat', 'Milk', 'Eggs', 'Soy'],
    ['Chocolate babka', 'A twisted loaf with dark chocolate running all the way through it. Serves three, or one determined person.'],
    ['Шоколадтай бабка', 'Хар шоколадыг дундуур нь мушгин оруулсан ороомог талх. Гурван хүнд, эсвэл шийдэмгий нэг хүнд хүрнэ.']),
  item('o14', 'm1', 'Sweet', 'turnover', 3800, 7600, 8, LOAF_C, ['Wheat', 'Milk', 'Eggs'],
    ['Apple turnover', 'Puff pastry folded over warm cinnamon apples, with sugar crackling on the lid.'],
    ['Алимтай эргүүлэг', 'Давхаргат гурил дотор нь халуун шанцайтай алим хийж нугалсан, дээрээ чихрийн царцдастай.']),
  item('o15', 'm1', 'Sweet', 'doughnut', 2600, 5200, 14, LOAF_C, ['Wheat', 'Milk', 'Eggs'],
    ['Custard doughnut', 'Soft, sugared and heavy with vanilla custard. Eat this one over a plate.'],
    ['Кремтэй донат', 'Зөөлөн, чихэр цацсан, ванилийн кремээр дүүрэн. Таваг дээрээ барьж идээрэй.']),
  item('o16', 'm1', 'Sweet', 'muffin', 3000, 6000, 11, LOAF_C, ['Wheat', 'Milk', 'Eggs'],
    ['Blueberry muffin', 'Tall and tender, full of berries that burst dark blue when you break it open.'],
    ['Нэрстэй маффин', 'Өндөр, зөөлөн. Хугалахад хөх нэрс нь цацран гарна.']),
  item('o17', 'm1', 'Sweet', 'cookie', 5600, 11200, 6, LOAF_B, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Box of butter cookies', 'Twelve small cookies from the last trays of the day. Good with tea, better with company.'],
    ['Цөцгийн тосны жигнэмэгийн хайрцаг', 'Өдрийн сүүлчийн тавиурын арван хоёр жижиг жигнэмэг. Цайтай сайхан, найзтай бол бүр сайхан.']),
  item('o18', 'm1', 'Sweet', 'poppy', 4300, 8600, 5, LOAF_B, ['Wheat', 'Milk', 'Eggs'],
    ['Poppy seed roll', 'A dark, fragrant spiral of poppy seed through a soft sweet dough.'],
    ['Намуу цэцгийн ороомог', 'Зөөлөн чихэрлэг зуурмаг дотор намуу цэцгийн үрийн бараан, анхилуун ороомог.']),
  item('o19', 'm1', 'Bakery', 'box', 8900, 19800, 3, LOAF_A, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Morning pastry box', 'Whatever is left on the shelves at closing, boxed up. Five or six pieces, chosen by the baker.'],
    ['Өглөөний нарийн боовны хайрцаг', 'Хаахад тавиур дээр үлдсэн бүхнийг хайрцаглав. Талхчны сонгосон таваас зургаан зүйл.']),
  item('o20', 'm1', 'Drinks', 'coffee', 2400, 4800, 8, LOAF_A, [],
    ['Filter coffee flask', 'Half a litre of the afternoon brew, poured into a flask to take with you.'],
    ['Шүүсэн кофены сав', 'Үдээс хойш чанасан хагас литр кофе, авч явах саванд хийсэн.']),
  item('o21', 'm1', 'Drinks', 'milktea', 2200, 4400, 9, LOAF_A, ['Milk'],
    ['Milk tea flask', 'Salted milk tea, still hot. Exactly what a cold walk home is for.'],
    ['Сүүтэй цайны сав', 'Давстай сүүтэй цай, одоо ч халуун. Хүйтэн замд яг таарна.']),
  item('o22', 'm1', 'Grocery', 'breadbag', 1800, 4500, 10, LOAF_C, ['Wheat', 'Sesame'],
    ['Bag of bread ends', 'The heels and offcuts of the day, by the bagful. For breadcrumbs, for soup, or for the birds.'],
    ['Талхны үзүүрийн уут', 'Өдрийн турш үлдсэн талхны үзүүр, огтлолууд бүтэн уутаар. Талхны үйрмэг, шөл, эсвэл шувуудад.']),

  // ---- m2 · Seoul Kitchen -------------------------------------------------
  item('o3', 'm2', 'Meals', '/assets/kimbap.jpg', 6500, 11000, 10, SEOUL_A, ['Eggs', 'Sesame', 'Soy', 'Fish', 'Wheat', 'Crustaceans'],
    ['Kimbap roll', 'Seasoned rice, crunchy vegetables, egg and crab sticks wrapped in seaweed. One full roll, sliced and ready for dinner.'],
    ['Кимбап ороомог', 'Амталсан цагаан будаа, шаржигнуур ногоо, өндөг, хавчны мах далайн байцаанд ороосон. Бүтэн нэг ороомог, зүсэж бэлдсэн, оройн хоолонд бэлэн.']),
  item('o23', 'm2', 'Meals', 'kimbap', 7200, 12000, 6, SEOUL_A, ['Sesame', 'Soy', 'Fish', 'Eggs'],
    ['Tuna kimbap', 'The same roll with tuna and a little mayonnaise through the middle. Filling on its own.'],
    ['Туна загастай кимбап', 'Мөн л тэр ороомог, дундуураа туна загас, багахан майонезтэй. Ганцаараа ч цадна.']),
  item('o24', 'm2', 'Meals', 'ricebowl', 8400, 14000, 5, SEOUL_A, ['Eggs', 'Sesame', 'Soy'],
    ['Bibimbap bowl', 'Rice under five seasoned vegetables and a fried egg. Stir it all together before the first bite.'],
    ['Бибимбап', 'Цагаан будаан дээр таван төрлийн амталсан ногоо, шарсан өндөг. Идэхийнхээ өмнө сайн хутгаарай.']),
  item('o25', 'm2', 'Meals', 'stew', 9200, 15500, 4, SEOUL_B, ['Soy', 'Fish'],
    ['Kimchi stew', 'A deep red pot of kimchi, tofu and pork, sold hot with a portion of rice.'],
    ['Кимчийн шөл', 'Кимчи, тофу, гахайн махтай улаан шөл. Халуунаар нь цагаан будаатай хамт.']),
  item('o26', 'm2', 'Meals', 'tteok', 6800, 11500, 7, SEOUL_B, ['Wheat', 'Soy', 'Fish', 'Sesame'],
    ['Tteokbokki', 'Chewy rice cakes in a sweet, properly spicy sauce. Not for the faint-hearted.'],
    ['Төкпокки', 'Зажлууртай будааны бялуу чихэрлэг, сайн халуун ноготой. Зоригтой хүнд зориулав.']),
  item('o27', 'm2', 'Meals', 'noodles', 7800, 13000, 6, SEOUL_A, ['Soy', 'Sesame', 'Eggs'],
    ['Japchae noodles', 'Glass noodles tossed with beef and vegetables in sesame oil. Good cold tomorrow, too.'],
    ['Чапчэ гоймон', 'Шилэн гоймонг үхрийн мах, ногоотой гүнжидийн тосонд хуурсан. Маргааш хүйтнээр нь ч сайхан.']),
  item('o28', 'm2', 'Meals', 'chicken', 12500, 21000, 4, SEOUL_B, ['Wheat', 'Soy', 'Sesame'],
    ['Fried chicken box', 'Twice-fried and glazed in soy and garlic. A box made to be shared and never is.'],
    ['Шарсан тахианы хайрцаг', 'Хоёр удаа шарж, шар буурцаг, саримсны ноогоор бүрсэн. Хуваах гэж хийсэн ч хэзээ ч хуваагддаггүй.']),
  item('o29', 'm2', 'Meals', 'ricebowl', 9600, 16000, 5, SEOUL_A, ['Soy', 'Sesame', 'Wheat'],
    ['Bulgogi rice box', 'Thin marinated beef over rice, with pickles on the side. Our steadiest seller.'],
    ['Пулгоги будаатай хайрцаг', 'Амталсан нимгэн үхрийн мах цагаан будаан дээр, хажууд нь даршилсан ногоо. Хамгийн их зарагддаг хоол.']),
  item('o30', 'm2', 'Meals', 'dumpling', 6200, 10500, 8, SEOUL_B, ['Wheat', 'Soy', 'Sesame'],
    ['Mandu dumplings', 'Ten steamed dumplings of pork and chive, with a small pot of dipping sauce.'],
    ['Манду', 'Гахайн мах, гоолинтой арван ширхэг жигнэсэн банш, жижиг аяга дүрэх ноотой.']),
  item('o31', 'm2', 'Meals', 'noodlesoup', 5900, 9800, 6, SEOUL_B, ['Wheat', 'Eggs', 'Soy'],
    ['Ramyeon set', 'A portion of spicy noodle soup with an egg and spring onion, packed to heat at home.'],
    ['Рамён багц', 'Халуун ногоотой гоймон шөл, өндөг, ногоон сонгинотой. Гэртээ халаахаар савлав.']),
  item('o32', 'm2', 'Meals', 'cutlet', 10500, 17500, 4, SEOUL_A, ['Wheat', 'Eggs', 'Milk', 'Soy'],
    ['Pork cutlet plate', 'Breadcrumbed pork, shredded cabbage and a dark sweet sauce. Rice underneath.'],
    ['Гахайн махны шницель', 'Талхны үйрмэгт хийж шарсан гахайн мах, нимгэн зүссэн байцаа, бараан чихэрлэг ноо. Доор нь цагаан будаа.']),
  item('o33', 'm2', 'Meals', 'soup', 5200, 8800, 7, SEOUL_B, ['Sesame', 'Soy', 'Fish'],
    ['Seaweed soup', 'Clear, mild and quietly restorative. The soup a Korean household makes on birthdays.'],
    ['Далайн байцааны шөл', 'Тунгалаг, зөөлөн, чимээгүйхэн тамир оруулна. Солонгос айл төрсөн өдрөөр чанадаг шөл.']),
  item('o34', 'm2', 'Meals', 'ricebowl', 8800, 14800, 5, SEOUL_A, ['Soy', 'Sesame'],
    ['Spicy pork bowl', 'Pork belly in gochujang over rice, with lettuce to wrap it in.'],
    ['Халуун ногоотой гахайн махны аяга', 'Кочужантай гахайн хэвлий цагаан будаан дээр, ороож идэх шанцайтай.']),
  item('o35', 'm2', 'Meals', 'pancake', 6600, 11000, 6, SEOUL_B, ['Wheat', 'Eggs', 'Soy', 'Crustaceans'],
    ['Seafood and spring onion pancake', 'Crisp at the edges, soft in the middle, cut into squares for sharing.'],
    ['Далайн хоол, ногоон сонгинотой хуушуур', 'Ирмэгээрээ хэврэг, дундаа зөөлөн. Хуваан идэхээр дөрвөлжин зүсэв.']),
  item('o36', 'm2', 'Meals', 'coldnoodles', 8200, 13800, 4, SEOUL_A, ['Wheat', 'Eggs', 'Soy', 'Sesame'],
    ['Cold buckwheat noodles', 'Chilled broth, thin buckwheat noodles, pear and egg. Made for a warm evening.'],
    ['Хүйтэн сагаг гоймон', 'Хөргөсөн шөл, нарийн сагаг гоймон, лийр, өндөг. Дулаан оройд зориулав.']),
  item('o37', 'm2', 'Sweet', 'ricecake', 4400, 7400, 8, SEOUL_A, ['Sesame', 'Nuts'],
    ['Honey rice cakes', 'Six small chewy cakes rolled in sesame and honey. Sweet, but not too sweet.'],
    ['Зөгийн балтай будааны бялуу', 'Гүнжид, зөгийн балд хольсон зажлууртай зургаан жижиг бялуу. Чихэрлэг ч хэтрээгүй.']),
  item('o38', 'm2', 'Sweet', 'redbean', 3600, 6000, 9, SEOUL_B, ['Wheat', 'Milk', 'Soy'],
    ['Sweet red bean bun', 'A soft steamed bun with smooth red bean paste inside. Best while still warm.'],
    ['Улаан буурцагтай боов', 'Зөөлөн жигнэсэн боов, дотроо гөлгөр улаан буурцагны зуурмагтай. Халуун байхад нь хамгийн сайхан.']),
  item('o39', 'm2', 'Drinks', 'tea', 2100, 3500, 12, SEOUL_A, [],
    ['Barley tea bottle', 'Roasted barley tea, chilled. A litre bottle that drinks like water but tastes of home.'],
    ['Арвайн цайны шил', 'Шарсан арвайн цай, хөргөсөн. Литрийн шил, ус шиг уугддаг ч гэрийн амттай.']),
  item('o40', 'm2', 'Drinks', 'juice', 3900, 6500, 6, SEOUL_B, [],
    ['Jar of yuzu tea', 'Citrus peel in honey. A spoonful in hot water and the whole kitchen smells better.'],
    ['Юзу цайны сав', 'Зөгийн бал дахь цитрусын хальс. Халуун усанд нэг халбага хийхэд гал тогоо бүхэлдээ анхилна.']),
  item('o41', 'm2', 'Grocery', 'kimchi', 4800, 8000, 7, SEOUL_B, ['Fish', 'Crustaceans'],
    ['Tub of house kimchi', 'Half a kilo of our own kimchi, three weeks old and getting better.'],
    ['Гэрийн кимчи сав', 'Өөрсдийн хийсэн хагас кило кимчи, гурван долоо хоногийн настай, улам сайжирсаар.']),

  // ---- m3 · Orchard Café --------------------------------------------------
  item('o4', 'm3', 'Sweet', '/assets/cake.jpg', 6900, 13800, 3, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Berry cake', 'One generous slice of soft cake, cream and bright berry layers. A little celebration, just because.'],
    ['Жимсний бялуу', 'Зөөлөн бялуу, цөцгий, тод жимсний давхаргатай өгөөмөр нэг зүсэм. Шалтгаангүйхэн ч гэсэн бяцхан баяр.']),
  item('o42', 'm3', 'Sweet', 'cake', 6400, 12800, 4, ORCHARD_A, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Carrot cake slice', 'Spiced, damp and thickly iced with cream cheese. Walnuts throughout.'],
    ['Луувантай бялууны зүсэм', 'Халуун ногоотой, чийглэг, дээрээ зузаан цөцгийн бяслагтай. Дундуураа хушганы мөхлөгтэй.']),
  item('o43', 'm3', 'Sweet', 'cheesecake', 7600, 15200, 4, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Baked cheesecake', 'A dense slice on a biscuit base, with sea buckthorn spooned over the top.'],
    ['Шарсан чизкейк', 'Жигнэмэгэн суурьтай нягт зүсэм, дээрээ чацарганы чанамалтай.']),
  item('o44', 'm3', 'Sweet', 'brownie', 4200, 8400, 9, ORCHARD_B, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Chocolate brownie', 'Fudgy in the middle, papery on top. One is plenty, and you will want two.'],
    ['Шоколадтай брауни', 'Дундаа зөөлөн, дээрээ нимгэн царцдастай. Нэг нь ч хангалттай ч хоёрыг хүсэх болно.']),
  item('o45', 'm3', 'Sweet', 'tart', 5800, 11600, 5, ORCHARD_B, ['Wheat', 'Milk', 'Eggs'],
    ['Lemon tart', 'Sharp lemon curd in a thin pastry shell, dusted with sugar.'],
    ['Нимбэгний тарт', 'Нимгэн гурилан сав дотор исгэлэн нимбэгний тос, дээрээ чихрийн нунтагтай.']),
  item('o46', 'm3', 'Sweet', 'eclair', 4600, 9200, 7, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Chocolate eclair', 'Choux pastry, vanilla cream and a dark chocolate lid. Made this morning.'],
    ['Шоколадтай эклер', 'Шү гурил, ванилийн крем, дээрээ хар шоколадан бүрхүүлтэй. Өнөө өглөө хийсэн.']),
  item('o47', 'm3', 'Sweet', 'macaron', 8800, 17600, 3, ORCHARD_A, ['Eggs', 'Milk', 'Nuts'],
    ['Box of six macarons', 'Whatever colours are left at the end of the day, in a ribboned box.'],
    ['Зургаан макароны хайрцаг', 'Өдрийн эцэст үлдсэн ямар ч өнгө, туузтай хайрцагт.']),
  item('o48', 'm3', 'Sweet', 'tiramisu', 6100, 12200, 5, ORCHARD_B, ['Wheat', 'Milk', 'Eggs'],
    ['Tiramisu cup', 'Coffee-soaked sponge and mascarpone in a glass, with cocoa over the top.'],
    ['Тирамису аяга', 'Кофенд норгосон бялуу, маскарпоне шилэн аяганд, дээрээ какаотой.']),
  item('o49', 'm3', 'Sweet', 'pie', 5400, 10800, 6, ORCHARD_B, ['Wheat', 'Milk', 'Eggs'],
    ['Apple pie slice', 'A proper wedge with a lattice lid, best warmed for a minute.'],
    ['Алимтай пирогийн зүсэм', 'Сүлжмэл бүрхүүлтэй том зүсэм. Нэг минут халаахад хамгийн сайхан.']),
  item('o50', 'm3', 'Sweet', 'fruittart', 5200, 10400, 6, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Fruit tartlet', 'Custard under whatever fruit came in this week, glazed to a shine.'],
    ['Жимсний бяцхан тарт', 'Энэ долоо хоногт ирсэн жимсний доор крем, дээрээ гялалзсан бүрхүүлтэй.']),
  item('o51', 'm3', 'Meals', 'quiche', 7400, 12400, 5, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Quiche slice', 'Leek, cheese and egg in shortcrust. Half a lunch on its own, a whole one with soup.'],
    ['Кишийн зүсэм', 'Гоолин, бяслаг, өндөг хэврэг гурилан суурин дээр. Ганцаараа хагас хоол, шөлтэй бол бүтэн.']),
  item('o52', 'm3', 'Meals', 'sandwich', 6800, 11400, 7, ORCHARD_B, ['Wheat', 'Milk', 'Eggs', 'Mustard'],
    ['Club sandwich', 'Chicken, egg and tomato in three layers, cut into four. Wrapped for the road.'],
    ['Клаб сэндвич', 'Тахианы мах, өндөг, улаан лооль гурван давхраар, дөрөв зүссэн. Замд зориулж боосон.']),
  item('o53', 'm3', 'Meals', 'soup', 4900, 8200, 8, ORCHARD_B, ['Milk'],
    ['Pumpkin soup', 'Half a litre, smooth and quietly sweet, with a swirl of cream on top.'],
    ['Хулуутай шөл', 'Хагас литр, гөлгөр, зөөлөн чихэрлэг. Дээрээ цөцгийн эргүүлэгтэй.']),
  item('o54', 'm3', 'Meals', 'salad', 5600, 9400, 6, ORCHARD_A, ['Milk', 'Mustard'],
    ['Garden salad bowl', 'Leaves, cucumber, radish and feta, with the dressing kept separate.'],
    ['Ногооны салат', 'Навчит ногоо, өргөст хэмх, улаан манжин, фета бяслаг. Ноог тусад нь савлав.']),
  item('o55', 'm3', 'Meals', 'toastie', 6200, 10400, 6, ORCHARD_B, ['Wheat', 'Milk', 'Mustard'],
    ['Ham and cheese toastie', 'Pressed until the cheese gives up. Wrapped hot, eaten hotter.'],
    ['Хиам, бяслагтай шарсан сэндвич', 'Бяслаг нь хайлтал дарж шарсан. Халуунаар нь боосон, бүр халуунаар нь идэх ёстой.']),
  item('o56', 'm3', 'Bakery', 'scone', 3300, 6600, 8, ORCHARD_A, ['Wheat', 'Milk', 'Eggs'],
    ['Butter scone', 'Plain and proud of it. Jam and cream are your business.'],
    ['Цөцгийн тосны скон', 'Энгийн бөгөөд түүгээрээ сайхан. Чанамал, цөцгий нь таны хэрэг.']),
  item('o57', 'm3', 'Bakery', 'painauchocolat', 4100, 8200, 7, ORCHARD_B, ['Wheat', 'Milk', 'Eggs', 'Soy'],
    ['Pain au chocolat', 'Two batons of dark chocolate in laminated pastry. Still shedding flakes.'],
    ['Шоколадтай боов', 'Давхаргат гурил дотор хоёр хар шоколадан саваа. Одоо ч үртэс нь унасаар.']),
  item('o58', 'm3', 'Drinks', 'icedcoffee', 3600, 6000, 8, ORCHARD_A, ['Milk'],
    ['Iced latte bottle', 'Espresso and cold milk in a sealed bottle. Shake before opening.'],
    ['Мөстэй латте шил', 'Эспрессо, хүйтэн сүү лацдсан шилэнд. Нээхийн өмнө сэгсрээрэй.']),
  item('o59', 'm3', 'Drinks', 'smoothie', 4200, 7000, 6, ORCHARD_B, ['Milk'],
    ['Berry smoothie', 'Yoghurt, banana and frozen berries. Thick enough to need a spoon.'],
    ['Жимсний смүүти', 'Тараг, гадил, хөлдөөсөн жимс. Халбага хэрэгтэй болтлоо өтгөн.']),
  item('o60', 'm3', 'Drinks', 'juice', 3400, 5800, 9, ORCHARD_B, [],
    ['Sea buckthorn lemonade', 'Bright orange, properly sour, made here with local sea buckthorn.'],
    ['Чацарганы лимонад', 'Тод улбар шар, зохих ёсоор исгэлэн. Нутгийн чацарганаар энд хийсэн.']),
  item('o61', 'm3', 'Sweet', 'box', 9800, 21000, 3, ORCHARD_A, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Patisserie surprise box', 'Four cakes from the counter, chosen by whoever is closing. No swaps, all lovely.'],
    ['Нарийн боовны гэнэтийн хайрцаг', 'Лангуунаас дөрвөн бялуу, хаалт хийж буй хүний сонголтоор. Солиулахгүй, бүгд сайхан.']),

  // ---- m4 · Steppe Table --------------------------------------------------
  item('o62', 'm4', 'Meals', 'buuz', 7500, 12500, 12, STEPPE_A, ['Wheat'],
    ['Ten buuz', 'Steamed mutton dumplings, folded this afternoon. The count is generous and always has been.'],
    ['Арван бууз', 'Өнөөдөр үдээс хойш хийсэн хонины махан бууз. Тоо нь өгөөмөр, урьдаас ч тийм байсан.']),
  item('o63', 'm4', 'Meals', 'khuushuur', 6000, 10000, 10, STEPPE_A, ['Wheat'],
    ['Five khuushuur', 'Fried flat and crisp at the edge, with plenty of juice inside. Hold it over the plate.'],
    ['Таван хуушуур', 'Хавтгайдаж шарсан, ирмэг нь хэврэг, дотроо шүүслэг. Таваг дээрээ барьж идээрэй.']),
  item('o64', 'm4', 'Meals', 'tsuivan', 7800, 13000, 8, STEPPE_A, ['Wheat'],
    ['Tsuivan', 'Hand-cut noodles steamed with mutton, cabbage and carrot. A full plate, no side needed.'],
    ['Цуйван', 'Гараар зүссэн гоймонг хонины мах, байцаа, луувантай жигнэсэн. Бүтэн таваг, хажуугийн хоол хэрэггүй.']),
  item('o65', 'm4', 'Meals', 'soup', 4600, 7800, 9, STEPPE_B, ['Wheat', 'Milk'],
    ['Bantan soup', 'Flour and mutton broth, thick and warm. What the family eats when it is minus thirty.'],
    ['Бантан', 'Гурил, хонины шөлтэй өтгөн, дулаахан. Хасах гуч градуст айл гэр юу иддэг билээ.']),
  item('o66', 'm4', 'Meals', 'noodlesoup', 5400, 9000, 9, STEPPE_B, ['Wheat'],
    ['Guriltai shul', 'Noodle soup with mutton and root vegetables. A litre, packed hot.'],
    ['Гурилтай шөл', 'Хонины мах, үндэст ногоотой гоймон шөл. Нэг литр, халуунаар савлав.']),
  item('o67', 'm4', 'Meals', 'ricebowl', 8200, 13700, 7, STEPPE_A, ['Wheat', 'Soy'],
    ['Budaatai khuurga', 'Fried rice with beef, onion and pepper. The lunch everyone in the office orders.'],
    ['Будаатай хуурга', 'Үхрийн мах, сонгино, чинжүүтэй хуурсан будаа. Оффисын бүх хүн захиалдаг үдийн хоол.']),
  item('o68', 'm4', 'Meals', 'khorkhog', 14500, 24000, 4, STEPPE_B, [],
    ['Khorkhog portion', 'Mutton cooked with hot stones, with potato and carrot from the same pot.'],
    ['Хорхогийн хувь', 'Халуун чулуугаар болгосон хонины мах, мөн тэр тогооны төмс, лууван.']),
  item('o69', 'm4', 'Meals', 'bansh', 6400, 10700, 8, STEPPE_A, ['Wheat'],
    ['Bansh in broth', 'Twenty small dumplings in a clear mutton broth. Soup and dinner at once.'],
    ['Банштай шөл', 'Тунгалаг хонины шөлөнд хорин жижиг банш. Шөл, оройн хоол хоёул нэг дор.']),
  item('o70', 'm4', 'Meals', 'goulash', 8900, 14800, 6, STEPPE_B, ['Wheat', 'Milk'],
    ['Goulash and mashed potato', 'Slow beef in a dark sauce, with butter mash beside it.'],
    ['Гуляш, нухсан төмс', 'Удаан чанасан үхрийн мах бараан ноотой, хажууд нь цөцгийн тостой нухсан төмс.']),
  item('o71', 'm4', 'Meals', 'cutlet', 7600, 12700, 7, STEPPE_A, ['Wheat', 'Eggs', 'Milk'],
    ['Beef cutlet plate', 'Two cutlets, rice and a spoon of pickled cabbage. Canteen cooking at its best.'],
    ['Үхрийн махан котлет', 'Хоёр котлет, цагаан будаа, нэг халбага даршилсан байцаа. Гуанзны хоолны шилдэг нь.']),
  item('o72', 'm4', 'Meals', 'potatosalad', 3800, 6400, 10, STEPPE_B, ['Eggs', 'Mustard'],
    ['Potato salad tub', 'Potato, egg, pickle and mayonnaise. Half a kilo, and it keeps until tomorrow.'],
    ['Төмсний салат', 'Төмс, өндөг, дарш, майонез. Хагас кило, маргааш хүртэл хадгална.']),
  item('o73', 'm4', 'Meals', 'salad', 3200, 5400, 9, STEPPE_B, [],
    ['Carrot salad tub', 'Grated carrot with garlic and a little oil. Sharp, and good beside anything fried.'],
    ['Лууванны салат', 'Үрсэн лууван, саримс, багахан тос. Хурц амттай, шарсан юмны хажууд сайхан.']),
  item('o74', 'm4', 'Bakery', 'mantuu', 2800, 4700, 12, STEPPE_A, ['Wheat'],
    ['Four steamed mantuu', 'Plain steamed buns to eat beside a stew, or split and fry them in the morning.'],
    ['Дөрвөн мантуу', 'Шөлний хажуугаар иддэг энгийн жигнэсэн боов. Өглөө нь хуваагаад шарж ч болно.']),
  item('o75', 'm4', 'Sweet', 'boortsog', 3400, 5700, 11, STEPPE_A, ['Wheat', 'Milk', 'Eggs'],
    ['Bag of boortsog', 'Fried dough, faintly sweet, in a bag big enough for a family. Dunk it in milk tea.'],
    ['Боорцогтой уут', 'Шарсан гурил, бага чихэрлэг. Айлд хүрэхүйц том уут. Сүүтэй цайнд дүрж идээрэй.']),
  item('o76', 'm4', 'Sweet', 'ulboov', 5200, 8700, 5, STEPPE_B, ['Wheat', 'Milk', 'Eggs'],
    ['Ul boov pieces', 'Four pieces of the patterned festival biscuit, from the tray we did not sell.'],
    ['Ул боовны хэсэг', 'Хээтэй баярын боовны дөрвөн хэсэг, зараагүй тавиураас.']),
  item('o77', 'm4', 'Sweet', 'aaruul', 4400, 7300, 9, STEPPE_B, ['Milk'],
    ['Bag of aaruul', 'Dried curd, hard as it should be. Two hundred grams of the sweeter kind.'],
    ['Ааруулын уут', 'Хатаасан ааруул, байх ёстойгоороо хатуу. Хоёр зуун грамм, чихэрлэг сортоос.']),
  item('o78', 'm4', 'Drinks', 'milktea', 2000, 3400, 14, STEPPE_A, ['Milk'],
    ['Suutei tsai flask', 'A litre of salted milk tea. The kettle is never off in this kitchen.'],
    ['Сүүтэй цайны сав', 'Литр давстай сүүтэй цай. Энэ гал тогоонд данх хэзээ ч унтардаггүй.']),
  item('o79', 'm4', 'Drinks', 'tarag', 3000, 5000, 8, STEPPE_B, ['Milk'],
    ['Tarag bottle', 'Home-set yoghurt, thick and sour. Drink it, or spoon it over boortsog.'],
    ['Тарагны шил', 'Гэрийн бүрсэн тараг, өтгөн, исгэлэн. Уух ч болно, боорцог дээрээ халбагадаж ч болно.']),
  item('o80', 'm4', 'Meals', 'box', 16500, 28000, 3, STEPPE_A, ['Wheat', 'Milk'],
    ['Family dinner box', 'Buuz, tsuivan and a litre of soup. Dinner for four, decided for you.'],
    ['Гэр бүлийн оройн хоолны хайрцаг', 'Бууз, цуйван, литр шөл. Дөрвөн хүний оройн хоол, сонголтыг нь бид хийлээ.']),
  item('o81', 'm4', 'Grocery', 'curd', 3600, 6000, 7, STEPPE_B, ['Milk'],
    ['Tub of fresh curd', 'Byaslag made this week, mild and crumbly. Good with bread and honey.'],
    ['Шинэ бяслагны сав', 'Энэ долоо хоногт хийсэн бяслаг, зөөлөн, хэврэг. Талх, зөгийн балтай сайхан.']),

  // ---- m5 · Blue Sky Grocer -----------------------------------------------
  item('o82', 'm5', 'Grocery', 'vegbox', 6900, 15000, 8, GROCER_A, [],
    ['Rescue vegetable box', 'Three kilos of whatever is too ripe for the shelf and perfect for a pot.'],
    ['Аврагдсан хүнсний ногооны хайрцаг', 'Тавиурт тавихад хэтэрхий болсон ч тогоонд яг таарах гурван кило ногоо.']),
  item('o83', 'm5', 'Grocery', 'fruitbox', 7400, 16000, 6, GROCER_A, [],
    ['Rescue fruit box', 'Apples, pears and whatever citrus is left. Eat some tonight, stew the rest.'],
    ['Аврагдсан жимсний хайрцаг', 'Алим, лийр, үлдсэн цитрус жимс. Заримыг нь өнөө орой идээд, үлдсэнийг нь чанаарай.']),
  item('o84', 'm5', 'Grocery', 'banana', 2200, 4500, 12, GROCER_B, [],
    ['Ripe bananas, one kilo', 'Freckled and sweet. Banana bread tomorrow if they last the night.'],
    ['Болсон гадил, нэг кило', 'Толботой, чихэрлэг. Шөнө дааваас маргааш гадилтай талх хийж болно.']),
  item('o85', 'm5', 'Grocery', 'apple', 3400, 6800, 10, GROCER_A, [],
    ['Bag of apples, two kilos', 'Small, firm and a little bruised. Exactly what a pie wants.'],
    ['Алимны уут, хоёр кило', 'Жижиг, хатуу, багахан няцарсан. Пирогт яг хэрэгтэй нь.']),
  item('o86', 'm5', 'Grocery', 'tomato', 2800, 5600, 9, GROCER_B, [],
    ['Soft tomatoes, one kilo', 'Too soft to slice, ideal for sauce. Use them within a day.'],
    ['Зөөлөрсөн улаан лооль, нэг кило', 'Зүсэхэд зөөлөн ч ноонд яг таарна. Нэг өдрийн дотор хэрэглээрэй.']),
  item('o87', 'm5', 'Grocery', 'potato', 3900, 7800, 8, GROCER_A, [],
    ['Potatoes, three kilos', 'Ordinary, honest potatoes at the end of the sack. They keep for weeks.'],
    ['Төмс, гурван кило', 'Шуудайны ёроолын энгийн сайн төмс. Хэдэн долоо хоног хадгална.']),
  item('o88', 'm5', 'Grocery', 'carrot', 2400, 4800, 11, GROCER_B, [],
    ['Carrots, two kilos', 'Bendy but sound. Soup, salad or the pot, all the same to them.'],
    ['Лууван, хоёр кило', 'Бага зэрэг уян ч эрүүл. Шөл, салат, тогоо — аль нь ч болно.']),
  item('o89', 'm5', 'Grocery', 'cabbage', 1900, 3800, 10, GROCER_A, [],
    ['Whole cabbage', 'A large head with the outer leaves taken off. Enough for two dinners.'],
    ['Бүтэн байцаа', 'Гадна навчийг нь авсан том толгой. Хоёр удаагийн оройн хоолонд хүрнэ.']),
  item('o90', 'm5', 'Grocery', 'onion', 2100, 4200, 12, GROCER_B, [],
    ['Net of onions, two kilos', 'Sprouting a little at the top. Below that, entirely fine.'],
    ['Сонгинын тор, хоёр кило', 'Дээрээ бага зэрэг соёолсон. Түүнээс доош нь бүрэн сайн.']),
  item('o91', 'm5', 'Grocery', 'cucumber', 2600, 5200, 9, GROCER_A, [],
    ['Cucumbers, six', 'Straight from the greenhouse row that did not sell. Crisp today, pickles tomorrow.'],
    ['Өргөст хэмх, зургаан ширхэг', 'Зараагүй хүлэмжийн эгнээнээс шууд. Өнөөдөр шаржигнуур, маргааш дарш.']),
  item('o92', 'm5', 'Grocery', 'milk', 2300, 4600, 14, GROCER_B, ['Milk'],
    ['Milk, one litre', 'One day from its date and perfectly good. Two bottles if you take them both.'],
    ['Сүү, нэг литр', 'Хугацаанаасаа нэг хоногийн өмнө, огт асуудалгүй. Хоёуланг нь авбал хоёр шил.']),
  item('o93', 'm5', 'Grocery', 'yoghurt', 3100, 6200, 10, GROCER_A, ['Milk'],
    ['Yoghurt, four pots', 'Plain set yoghurt, close to date. Honey and aaruul are your own affair.'],
    ['Тараг, дөрвөн аяга', 'Энгийн бүрсэн тараг, хугацаа нь ойртсон. Зөгийн бал, ааруул нь таны хэрэг.']),
  item('o94', 'm5', 'Grocery', 'cheese', 5800, 11600, 6, GROCER_B, ['Milk'],
    ['Wedge of cheese, 400 g', 'A cut end from the deli block. The rind is fine, the cheese is better.'],
    ['Бяслагны зүсэм, 400 г', 'Лангууны бүтэн бяслагны үзүүр. Хальс нь ч сайн, бяслаг нь бүр сайн.']),
  item('o95', 'm5', 'Grocery', 'butter', 4200, 8400, 8, GROCER_A, ['Milk'],
    ['Butter, 200 g', 'Unsalted, close to date, and destined for pastry.'],
    ['Цөцгийн тос, 200 г', 'Давсгүй, хугацаа нь ойртсон, нарийн боовонд зориулагдсан.']),
  item('o96', 'm5', 'Grocery', 'eggs', 3600, 7200, 9, GROCER_B, ['Eggs'],
    ['Ten eggs', 'From a tray with two broken ones taken out. The other ten are untouched.'],
    ['Арван өндөг', 'Хоёр хагарсныг нь авсан тавцангаас. Үлдсэн арав нь бүрэн бүтэн.']),
  item('o97', 'm5', 'Bakery', 'loaf', 1600, 3200, 12, GROCER_A, ['Wheat', 'Soy'],
    ['Day-old sliced bread', 'Yesterday’s loaf at half the price. Toast it and you will not know.'],
    ['Өчигдрийн зүсмэл талх', 'Өчигдрийн талх хагас үнээр. Шарчихвал ялгааг нь мэдэхгүй.']),
  item('o98', 'm5', 'Meals', 'chicken', 11500, 19000, 5, GROCER_A, [],
    ['Deli roast chicken', 'A whole bird from the hot counter, taken off at closing time.'],
    ['Лангууны шарсан тахиа', 'Халуун лангуунаас бүтэн тахиа, хаах цагт буулгасан.']),
  item('o99', 'm5', 'Meals', 'salad', 4400, 8800, 7, GROCER_B, ['Eggs', 'Milk', 'Mustard'],
    ['Ready salad bowl', 'Made here this morning: leaves, chicken, egg and dressing in the lid.'],
    ['Бэлэн салатны аяга', 'Өнөө өглөө энд хийсэн: ногоо, тахианы мах, өндөг, ноог таганд нь хийв.']),
  item('o100', 'm5', 'Drinks', 'juice', 2900, 5800, 11, GROCER_B, [],
    ['Orange juice, one litre', 'Not from concentrate, two days from its date, entirely delicious.'],
    ['Жүржийн жүүс, нэг литр', 'Өтгөрүүлээгүй, хугацаанаасаа хоёр хоногийн өмнө, бүрэн амттай.']),
  item('o101', 'm5', 'Drinks', 'juice', 3800, 7600, 8, GROCER_A, [],
    ['Sea buckthorn juice, one litre', 'Local, unsweetened and very good for you, which you can taste.'],
    ['Чацарганы жүүс, нэг литр', 'Нутгийн, чихэргүй, эрүүл мэндэд тустай. Тэгээд тэр нь амтанд нь мэдрэгдэнэ.']),

  // ---- m6 · Sansar Coffee House -------------------------------------------
  item('o102', 'm6', 'Grocery', 'beans', 12800, 21500, 5, SANSAR_A, [],
    ['Bag of espresso beans, 250 g', 'Roasted eleven days ago, which is past our shelf rule and nobody else’s.'],
    ['Эспрессо шош, 250 г', 'Арван нэг хоногийн өмнө шарсан. Манай дүрмээр хугацаа нь өнгөрсөн ч бусдынхаар үгүй.']),
  item('o103', 'm6', 'Drinks', 'coffee', 2600, 4400, 10, SANSAR_A, [],
    ['Filter coffee flask', 'Half a litre of today’s single origin, black and still hot.'],
    ['Шүүсэн кофены сав', 'Өнөөдрийн нэг гаралтай хагас литр кофе, сүүгүй, одоо ч халуун.']),
  item('o104', 'm6', 'Drinks', 'coldbrew', 3800, 6400, 9, SANSAR_B, [],
    ['Cold brew bottle', 'Steeped eighteen hours. Strong enough that one bottle is two servings.'],
    ['Хүйтэн дэвтээсэн кофены шил', 'Арван найман цаг дэвтээсэн. Нэг шил нь хоёр хүний хувь болохоор хүчтэй.']),
  item('o105', 'm6', 'Drinks', 'latte', 3400, 5700, 8, SANSAR_A, ['Milk', 'Soy'],
    ['Oat latte', 'Double shot with oat milk, sealed in a cup that will survive the walk.'],
    ['Овъёосны сүүтэй латте', 'Давхар шот, овъёосны сүүтэй. Замд тэсэх аяганд лацдсан.']),
  item('o106', 'm6', 'Drinks', 'mocha', 3900, 6500, 7, SANSAR_B, ['Milk'],
    ['Mocha', 'Espresso, dark chocolate and steamed milk. Dessert that pretends to be coffee.'],
    ['Мокка', 'Эспрессо, хар шоколад, уураар халаасан сүү. Кофе мэт дүр эсгэсэн амттан.']),
  item('o107', 'm6', 'Drinks', 'matcha', 4200, 7000, 6, SANSAR_A, ['Milk'],
    ['Matcha latte', 'Whisked properly, not scooped from a tin of powder and sugar.'],
    ['Матча латте', 'Ёсоор нь хутгаж хийсэн, нунтаг чихрийн лаазнаас утгасан биш.']),
  item('o108', 'm6', 'Drinks', 'chocolate', 3600, 6000, 8, SANSAR_B, ['Milk'],
    ['Hot chocolate', 'Real chocolate melted into milk. Thick, and unapologetic about it.'],
    ['Халуун шоколад', 'Жинхэнэ шоколадыг сүүнд хайлуулсан. Өтгөн, түүнийхээ төлөө уучлал гуйхгүй.']),
  item('o109', 'm6', 'Drinks', 'chai', 3300, 5500, 7, SANSAR_A, ['Milk'],
    ['Chai latte', 'Cardamom, ginger and black tea, brewed in milk rather than stirred into it.'],
    ['Чай латте', 'Кардамон, цагаан гаа, хар цай. Сүүнд хутгасан биш, сүүн дотор чанасан.']),
  item('o110', 'm6', 'Drinks', 'tea', 2800, 4700, 9, SANSAR_B, [],
    ['Pot of herbal tea', 'Sea buckthorn, thyme and rosehip, in a flask for two.'],
    ['Ургамлын цайны сав', 'Чацаргана, ганга, нохойн хошуу. Хоёр хүний саванд.']),
  item('o111', 'm6', 'Drinks', 'icedcoffee', 3100, 5200, 10, SANSAR_A, [],
    ['Iced americano', 'Two shots over ice, no milk, no sugar, no argument.'],
    ['Мөстэй американо', 'Мөсөн дээр хоёр шот. Сүүгүй, чихэргүй, маргаангүй.']),
  item('o112', 'm6', 'Sweet', 'bananabread', 3700, 6200, 8, SANSAR_A, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Banana bread slice', 'A thick slice, damp in the middle, better on the second day.'],
    ['Гадилтай талхны зүсэм', 'Зузаан зүсэм, дундаа чийглэг. Хоёр дахь өдөр нь илүү сайхан.']),
  item('o113', 'm6', 'Sweet', 'cookie', 3900, 6500, 9, SANSAR_B, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Three cookies', 'One chocolate, one oat, one whatever the baker felt like. Still soft.'],
    ['Гурван жигнэмэг', 'Нэг шоколадтай, нэг овъёостой, нэг нь талхчны сэтгэлээр. Одоо ч зөөлөн.']),
  item('o114', 'm6', 'Bakery', 'knot', 3500, 5900, 8, SANSAR_A, ['Wheat', 'Milk', 'Eggs'],
    ['Cinnamon knot', 'Cardamom in the dough, sugar on the crust. The Nordic kind, not the sticky kind.'],
    ['Шанцайны боодол', 'Зуурмагт нь кардамон, царцдас дээр нь чихэр. Наалдамхай биш, хойд Европынх.']),
  item('o115', 'm6', 'Bakery', 'croissant', 4900, 8200, 6, SANSAR_B, ['Wheat', 'Milk', 'Eggs', 'Mustard'],
    ['Ham and cheese croissant', 'Split, filled and toasted to order this morning. Reheats beautifully.'],
    ['Хиам, бяслагтай круассан', 'Өнөө өглөө захиалгаар зүсэж, дүүргэж, шарсан. Дахин халаахад гайхалтай.']),
  item('o116', 'm6', 'Bakery', 'bagel', 4400, 7400, 7, SANSAR_A, ['Wheat', 'Milk', 'Sesame'],
    ['Bagel with cream cheese', 'Toasted, thickly spread, wrapped in paper. Breakfast at four in the afternoon.'],
    ['Цөцгийн бяслагтай бэйгл', 'Шарсан, зузаан түрхсэн, цаасанд боосон. Үдээс хойш дөрвөн цагийн өглөөний хоол.']),
  item('o117', 'm6', 'Meals', 'toast', 5600, 9400, 6, SANSAR_B, ['Wheat', 'Sesame'],
    ['Avocado toast', 'Sourdough, smashed avocado, chilli and lime. Assembled when you collect it.'],
    ['Авокадотой шарсан талх', 'Исгэсэн зуурмагийн талх, нухсан авокадо, чинжүү, лайм. Авахад тань угсарч өгнө.']),
  item('o118', 'm6', 'Meals', 'wrap', 6300, 10500, 7, SANSAR_A, ['Wheat', 'Eggs', 'Milk'],
    ['Breakfast wrap', 'Egg, cheese and spinach in a warm tortilla. Wrapped tight for one hand.'],
    ['Өглөөний ролл', 'Өндөг, бяслаг, бууцай дулаан тортильяд. Нэг гараар барихаар чанга боосон.']),
  item('o119', 'm6', 'Meals', 'soup', 4800, 8000, 8, SANSAR_B, ['Milk', 'Celery'],
    ['Soup of the day', 'Half a litre of whatever the kitchen made this morning, with bread on the side.'],
    ['Өдрийн шөл', 'Өнөө өглөө гал тогооны хийсэн хагас литр шөл, хажууд нь талх.']),
  item('o120', 'm6', 'Sweet', 'granola', 4100, 6900, 7, SANSAR_A, ['Milk', 'Nuts'],
    ['Granola and yoghurt cup', 'Layered this morning: oats, honey, yoghurt and berries in a glass.'],
    ['Гранола, тарагны аяга', 'Өнөө өглөө давхарлав: овъёос, зөгийн бал, тараг, жимс шилэн аяганд.']),
  item('o121', 'm6', 'Bakery', 'box', 7800, 16500, 4, SANSAR_B, ['Wheat', 'Milk', 'Eggs', 'Nuts'],
    ['Pastry surprise bag', 'Three or four pastries from the case, whatever the last hour leaves us.'],
    ['Нарийн боовны гэнэтийн уут', 'Лангуунаас гурав, дөрвөн нарийн боов. Сүүлийн цагт юу үлдсэнээс шалтгаална.']),
];

/* Items that do not come back tomorrow: a one-off tray, the last of a
   batch, a box built from whatever was left. Everything else is a standing
   listing the shop set up once, which is how a bakery actually uses this. */
const ONE_OFF = new Set(['o19', 'o61', 'o121', 'o68', 'o76', 'o80', 'o102', 'o98']);
for (const entry of ITEMS) entry.recurring = !ONE_OFF.has(entry.id);

export const ITEM_IDS = ITEMS.map(entry => entry.id);

/* Published as flat `demo.*` keys because that is the shape content.js already
   looks up, and a merchant's own item — which has no entry here — has to fall
   through to the words they typed. */
export function demoStrings(language) {
  const strings = {};
  for (const shop of SHOPS) {
    if (shop.mnName && language === 'mn') strings[`demo.shop.${shop.id}.name`] = shop.mnName;
    strings[`demo.shop.${shop.id}.address`] = shop[language].address;
    strings[`demo.shop.${shop.id}.pickupNote`] = shop[language].pickupNote;
    strings[`demo.shop.${shop.id}.kind`] = shop[language].kind;
  }
  for (const entry of ITEMS) {
    strings[`demo.offer.${entry.id}.title`] = entry[language].title;
    strings[`demo.offer.${entry.id}.description`] = entry[language].description;
  }
  return strings;
}
